#!/bin/bash
python3 darknet_video.py --data_file obj.data --config_file yolo-obj.cfg --weights yolo-obj_best.weights --thresh 0.25 --dont_show --input test2.mp4 --export_logname results.txt --out_filename out.mp4
