#!/bin/bash
python3 -u darknet_video.py --data_file obj.data --config_file yolo608-obj.cfg --weights yolo608-obj_best.weights --thresh 0.25 --dont_show --input test2.mp4 --export_logname results.txt --out_filename out.mp4 > last_run_outstream.txt 2>&1
